language: c++
sudo: false
matrix:
  fast_finish: true
  include:
    - name: MaxOs clang
      os: osx
      compiler: clang
      env: CXX="clang++" CC="clang" BUILD_TYPE=release
    - name: Ubuntu 18.04 gcc
      os: linux
      dist: bionic
      compiler: gcc
      env: CXX="g++" CC="gcc" BUILD_TYPE=release
    - name: Ubuntu 18.04 clang
      os: linux
      dist: bionic
      compiler: clang
      env: CXX="clang++" CC="clang" BUILD_TYPE=release

before_install:
  - chmod +x ./scripts/install_dependencies.sh && ./scripts/install_dependencies.sh

script:
  - CC="$CC" CXX="$CXX" cmake . -DENABLE_BENCHMARK=On -DENABLE_TEST=On
  - make -j4 VERBOSE=1
  - make test
  - make benchmark